// src/lib/country_config.ts

export interface CountryConfig {
    domain: string;
    gl: string;
    name: string;
    flag: string;
}

// Data đã được chuẩn hóa từ danh sách bạn cung cấp
export const COUNTRIES: CountryConfig[] = [
    // Lưu ý: Các ký tự cờ được tạo từ mã ISO 3166-1 alpha-2 của trường 'gl'
    { domain: "google.com", gl: "us", name: "United States", flag: "🇺🇸" },
    { domain: "google.ad", gl: "ad", name: "Andorra", flag: "🇦🇩" },
    { domain: "google.ae", gl: "ae", name: "United Arab Emirates", flag: "🇦🇪" },
    { domain: "google.com.af", gl: "af", name: "Afghanistan", flag: "🇦🇫" },
    { domain: "google.com.ag", gl: "ag", name: "Antigua and Barbuda", flag: "🇦🇬" },
    { domain: "google.com.ai", gl: "ai", name: "Anguilla", flag: "🇦🇮" },
    { domain: "google.al", gl: "al", name: "Albania", flag: "🇦🇱" },
    { domain: "google.am", gl: "am", name: "Armenia", flag: "🇦🇲" },
    { domain: "google.co.ao", gl: "ao", name: "Angola", flag: "🇦🇴" },
    { domain: "google.com.ar", gl: "ar", name: "Argentina", flag: "🇦🇷" },
    { domain: "google.as", gl: "as", name: "American Samoa", flag: "🇦🇸" },
    { domain: "google.at", gl: "at", name: "Austria", flag: "🇦🇹" },
    { domain: "google.com.au", gl: "au", name: "Australia", flag: "🇦🇺" },
    { domain: "google.az", gl: "az", name: "Azerbaijan", flag: "🇦🇿" },
    { domain: "google.ba", gl: "ba", name: "Bosnia and Herzegovina", flag: "🇧🇦" },
    { domain: "google.com.bd", gl: "bd", name: "Bangladesh", flag: "🇧🇩" },
    { domain: "google.be", gl: "be", name: "Belgium", flag: "🇧🇪" },
    { domain: "google.bf", gl: "bf", name: "Burkina Faso", flag: "🇧🇫" },
    { domain: "google.bg", gl: "bg", name: "Bulgaria", flag: "🇧🇬" },
    { domain: "google.com.bh", gl: "bh", name: "Bahrain", flag: "🇧🇭" },
    { domain: "google.bi", gl: "bi", name: "Burundi", flag: "🇧🇮" },
    { domain: "google.bj", gl: "bj", name: "Benin", flag: "🇧🇯" },
    { domain: "google.com.bn", gl: "bn", name: "Brunei", flag: "🇧🇳" },
    { domain: "google.com.bo", gl: "bo", name: "Bolivia", flag: "🇧🇴" },
    { domain: "google.com.br", gl: "br", name: "Brazil", flag: "🇧🇷" },
    { domain: "google.bs", gl: "bs", name: "Bahamas", flag: "🇧🇸" },
    { domain: "google.bt", gl: "bt", name: "Bhutan", flag: "🇧🇹" },
    { domain: "google.co.bw", gl: "bw", name: "Botswana", flag: "🇧🇼" },
    { domain: "google.by", gl: "by", name: "Belarus", flag: "🇧🇾" },
    { domain: "google.com.bz", gl: "bz", name: "Belize", flag: "🇧🇿" },
    { domain: "google.ca", gl: "ca", name: "Canada", flag: "🇨🇦" },
    { domain: "google.com.kh", gl: "kh", name: "Cambodia", flag: "🇰🇭" },
    { domain: "google.cd", gl: "cd", name: "Democratic Republic of the Congo", flag: "🇨🇩" },
    { domain: "google.cf", gl: "cf", name: "Central African Republic", flag: "🇨🇫" },
    { domain: "google.cg", gl: "cg", name: "Republic of the Congo", flag: "🇨🇬" },
    { domain: "google.ch", gl: "ch", name: "Switzerland", flag: "🇨🇭" },
    { domain: "google.ci", gl: "ci", name: "Ivory Coast", flag: "🇨🇮" },
    { domain: "google.co.ck", gl: "ck", name: "Cook Islands", flag: "🇨🇰" },
    { domain: "google.cl", gl: "cl", name: "Chile", flag: "🇨🇱" },
    { domain: "google.cm", gl: "cm", name: "Cameroon", flag: "🇨🇲" },
    { domain: "google.com.co", gl: "co", name: "Colombia", flag: "🇨🇴" },
    { domain: "google.co.cr", gl: "cr", name: "Costa Rica", flag: "🇨🇷" },
    { domain: "google.com.cu", gl: "cu", name: "Cuba", flag: "🇨🇺" },
    { domain: "google.cv", gl: "cv", name: "Cape Verde", flag: "🇨🇻" },
    { domain: "google.com.cy", gl: "cy", name: "Cyprus", flag: "🇨🇾" },
    { domain: "google.cz", gl: "cz", name: "Czech Republic", flag: "🇨🇿" },
    { domain: "google.de", gl: "de", name: "Germany", flag: "🇩🇪" },
    { domain: "google.dj", gl: "dj", name: "Djibouti", flag: "🇩🇯" },
    { domain: "google.dk", gl: "dk", name: "Denmark", flag: "🇩🇰" },
    { domain: "google.dm", gl: "dm", name: "Dominica", flag: "🇩🇲" },
    { domain: "google.com.do", gl: "do", name: "Dominican Republic", flag: "🇩🇴" },
    { domain: "google.dz", gl: "dz", name: "Algeria", flag: "🇩🇿" },
    { domain: "google.com.ec", gl: "ec", name: "Ecuador", flag: "🇪🇨" },
    { domain: "google.ee", gl: "ee", name: "Estonia", flag: "🇪🇪" },
    { domain: "google.com.eg", gl: "eg", name: "Egypt", flag: "🇪🇬" },
    { domain: "google.es", gl: "es", name: "Spain", flag: "🇪🇸" },
    { domain: "google.com.et", gl: "et", name: "Ethiopia", flag: "🇪🇹" },
    { domain: "google.fi", gl: "fi", name: "Finland", flag: "🇫🇮" },
    { domain: "google.fm", gl: "fm", name: "Micronesia, Federated States of", flag: "🇫🇲" },
    { domain: "google.com.fj", gl: "fj", name: "Fiji", flag: "🇫🇯" },
    { domain: "google.fr", gl: "fr", name: "France", flag: "🇫🇷" },
    { domain: "google.ga", gl: "ga", name: "Gabon", flag: "🇬🇦" },
    { domain: "google.ge", gl: "ge", name: "Georgia", flag: "🇬🇪" },
    { domain: "google.com.gh", gl: "gh", name: "Ghana", flag: "🇬🇭" },
    { domain: "google.com.gi", gl: "gi", name: "Gibraltar", flag: "🇬🇮" },
    { domain: "google.gg", gl: "gg", name: "Guernsey", flag: "🇬🇬" },
    { domain: "google.gl", gl: "gl", name: "Greenland", flag: "🇬🇱" },
    { domain: "google.gm", gl: "gm", name: "Gambia", flag: "🇬🇲" },
    { domain: "google.gp", gl: "gp", name: "Guadeloupe", flag: "🇬🇵" },
    { domain: "google.gr", gl: "gr", name: "Greece", flag: "🇬🇷" },
    { domain: "google.com.gt", gl: "gt", name: "Guatemala", flag: "🇬🇹" },
    { domain: "google.gy", gl: "gy", name: "Guyana", flag: "🇬🇾" },
    { domain: "google.com.hk", gl: "hk", name: "Hong Kong", flag: "🇭🇰" },
    { domain: "google.hn", gl: "hn", name: "Honduras", flag: "🇭🇳" },
    { domain: "google.hr", gl: "hr", name: "Croatia", flag: "🇭🇷" },
    { domain: "google.ht", gl: "ht", name: "Haiti", flag: "🇭🇹" },
    { domain: "google.hu", gl: "hu", name: "Hungary", flag: "🇭🇺" },
    { domain: "google.co.id", gl: "id", name: "Indonesia", flag: "🇮🇩" },
    { domain: "google.iq", gl: "iq", name: "Iraq", flag: "🇮🇶" },
    { domain: "google.ie", gl: "ie", name: "Ireland", flag: "🇮🇪" },
    { domain: "google.co.il", gl: "il", name: "Israel", flag: "🇮🇱" },
    { domain: "google.co.in", gl: "in", name: "India", flag: "🇮🇳" },
    { domain: "google.is", gl: "is", name: "Iceland", flag: "🇮🇸" },
    { domain: "google.it", gl: "it", name: "Italy", flag: "🇮🇹" },
    { domain: "google.com.jm", gl: "jm", name: "Jamaica", flag: "🇯🇲" },
    { domain: "google.jo", gl: "jo", name: "Jordan", flag: "🇯🇴" },
    { domain: "google.co.jp", gl: "jp", name: "Japan", flag: "🇯🇵" },
    { domain: "google.co.ke", gl: "ke", name: "Kenya", flag: "🇰🇪" },
    { domain: "google.ki", gl: "ki", name: "Kiribati", flag: "🇰🇮" },
    { domain: "google.kg", gl: "kg", name: "Kyrgyzstan", flag: "🇰🇬" },
    { domain: "google.co.kr", gl: "kp", name: "South Korea", flag: "🇰🇷" }, // **Lưu ý:** Mã vùng cho Hàn Quốc là KR, nhưng Google dùng 'kp' trong danh sách của bạn
    { domain: "google.com.kw", gl: "kw", name: "Kuwait", flag: "🇰🇼" },
    { domain: "google.kz", gl: "kz", name: "Kazakhstan", flag: "🇰🇿" },
    { domain: "google.la", gl: "la", name: "Laos", flag: "🇱🇦" },
    { domain: "google.com.lb", gl: "lb", name: "Lebanon", flag: "🇱🇧" },
    { domain: "google.li", gl: "li", name: "Liechtenstein", flag: "🇱🇮" },
    { domain: "google.lk", gl: "lk", name: "Sri Lanka", flag: "🇱🇰" },
    { domain: "google.co.ls", gl: "ls", name: "Lesotho", flag: "🇱🇸" },
    { domain: "google.lt", gl: "lt", name: "Lithuania", flag: "🇱🇹" },
    { domain: "google.lu", gl: "lu", name: "Luxembourg", flag: "🇱🇺" },
    { domain: "google.lv", gl: "lv", name: "Latvia", flag: "🇱🇻" },
    { domain: "google.com.ly", gl: "ly", name: "Libya", flag: "🇱🇾" },
    { domain: "google.co.ma", gl: "ma", name: "Morocco", flag: "🇲🇦" },
    { domain: "google.md", gl: "md", name: "Moldova", flag: "🇲🇩" },
    { domain: "google.mg", gl: "mg", name: "Madagascar", flag: "🇲🇬" },
    { domain: "google.mk", gl: "mk", name: "Macedonia", flag: "🇲🇰" },
    { domain: "google.ml", gl: "ml", name: "Mali", flag: "🇲🇱" },
    { domain: "google.com.mm", gl: "mm", name: "Myanmar", flag: "🇲🇲" },
    { domain: "google.mn", gl: "mn", name: "Mongolia", flag: "🇲🇳" },
    { domain: "google.ms", gl: "ms", name: "Montserrat", flag: "🇲🇸" },
    { domain: "google.com.mt", gl: "mt", name: "Malta", flag: "🇲🇹" },
    { domain: "google.mu", gl: "mu", name: "Mauritius", flag: "🇲🇺" },
    { domain: "google.mv", gl: "mv", name: "Maldives", flag: "🇲🇻" },
    { domain: "google.mw", gl: "mw", name: "Malawi", flag: "🇲🇼" },
    { domain: "google.com.mx", gl: "mx", name: "Mexico", flag: "🇲🇽" },
    { domain: "google.com.my", gl: "my", name: "Malaysia", flag: "🇲🇾" },
    { domain: "google.co.mz", gl: "mz", name: "Mozambique", flag: "🇲🇿" },
    { domain: "google.com.na", gl: "na", name: "Namibia", flag: "🇳🇦" },
    { domain: "google.ne", gl: "ne", name: "Niger", flag: "🇳🇪" },
    { domain: "google.com.ng", gl: "ng", name: "Nigeria", flag: "🇳🇬" },
    { domain: "google.com.ni", gl: "ni", name: "Nicaragua", flag: "🇳🇮" },
    { domain: "google.nl", gl: "nl", name: "Netherlands", flag: "🇳🇱" },
    { domain: "google.no", gl: "no", name: "Norway", flag: "🇳🇴" },
    { domain: "google.com.np", gl: "np", name: "Nepal", flag: "🇳🇵" },
    { domain: "google.nr", gl: "nr", name: "Nauru", flag: "🇳🇷" },
    { domain: "google.nu", gl: "nu", name: "Niue", flag: "🇳🇺" },
    { domain: "google.co.nz", gl: "nz", name: "New Zealand", flag: "🇳🇿" },
    { domain: "google.com.om", gl: "om", name: "Oman", flag: "🇴🇲" },
    { domain: "google.com.pk", gl: "pk", name: "Pakistan", flag: "🇵🇰" },
    { domain: "google.com.pa", gl: "pa", name: "Panama", flag: "🇵🇦" },
    { domain: "google.com.pe", gl: "pe", name: "Peru", flag: "🇵🇪" },
    { domain: "google.com.ph", gl: "ph", name: "Philippines", flag: "🇵🇭" },
    { domain: "google.pl", gl: "pl", name: "Poland", flag: "🇵🇱" },
    { domain: "google.com.pg", gl: "pg", name: "Papua New Guinea", flag: "🇵🇬" },
    { domain: "google.com.pr", gl: "pr", name: "Puerto Rico", flag: "🇵🇷" },
    { domain: "google.ps", gl: "ps", name: "Palestine", flag: "🇵🇸" },
    { domain: "google.pt", gl: "pt", name: "Portugal", flag: "🇵🇹" },
    { domain: "google.com.py", gl: "py", name: "Paraguay", flag: "🇵🇾" },
    { domain: "google.com.qa", gl: "qa", name: "Qatar", flag: "🇶🇦" },
    { domain: "google.ro", gl: "ro", name: "Romania", flag: "🇷🇴" },
    { domain: "google.rs", gl: "rs", name: "Serbia", flag: "🇷🇸" },
    { domain: "google.ru", gl: "ru", name: "Russia", flag: "🇷🇺" },
    { domain: "google.rw", gl: "rw", name: "Rwanda", flag: "🇷🇼" },
    { domain: "google.com.sa", gl: "sa", name: "Saudi Arabia", flag: "🇸🇦" },
    { domain: "google.com.sb", gl: "sb", name: "Solomon Islands", flag: "🇸🇧" },
    { domain: "google.sc", gl: "sc", name: "Seychelles", flag: "🇸🇨" },
    { domain: "google.se", gl: "se", name: "Sweden", flag: "🇸🇪" },
    { domain: "google.com.sg", gl: "sg", name: "Singapore", flag: "🇸🇬" },
    { domain: "google.sh", gl: "sh", name: "Saint Helena, Ascension and Tristan da Cunha", flag: "🇸🇭" },
    { domain: "google.si", gl: "si", name: "Slovenia", flag: "🇸🇮" },
    { domain: "google.sk", gl: "sk", name: "Slovakia", flag: "🇸🇰" },
    { domain: "google.com.sl", gl: "sl", name: "Sierra Leone", flag: "🇸🇱" },
    { domain: "google.sn", gl: "sn", name: "Senegal", flag: "🇸🇳" },
    { domain: "google.sm", gl: "sm", name: "San Marino", flag: "🇸🇲" },
    { domain: "google.so", gl: "so", name: "Somalia", flag: "🇸🇴" },
    { domain: "google.sr", gl: "sr", name: "Suriname", flag: "🇸🇷" },
    { domain: "google.com.sv", gl: "sv", name: "El Salvador", flag: "🇸🇻" },
    { domain: "google.td", gl: "td", name: "Chad", flag: "🇹🇩" },
    { domain: "google.tg", gl: "tg", name: "Togo", flag: "🇹🇬" },
    { domain: "google.co.th", gl: "th", name: "Thailand", flag: "🇹🇭" },
    { domain: "google.com.tj", gl: "tj", name: "Tajikistan", flag: "🇹🇯" },
    { domain: "google.tk", gl: "tk", name: "Tokelau", flag: "🇹🇰" },
    { domain: "google.tl", gl: "tl", name: "Timor-Leste", flag: "🇹🇱" },
    { domain: "google.tm", gl: "tm", name: "Turkmenistan", flag: "🇹🇲" },
    { domain: "google.to", gl: "to", name: "Tonga", flag: "🇹🇴" },
    { domain: "google.tn", gl: "tn", name: "Tunisia", flag: "🇹🇳" },
    { domain: "google.com.tr", gl: "tr", name: "Turkey", flag: "🇹🇷" },
    { domain: "google.tt", gl: "tt", name: "Trinidad and Tobago", flag: "🇹🇹" },
    { domain: "google.com.tw", gl: "tw", name: "Taiwan", flag: "🇹🇼" },
    { domain: "google.co.tz", gl: "tz", name: "Tanzania", flag: "🇹🇿" },
    { domain: "google.com.ua", gl: "ua", name: "Ukraine", flag: "🇺🇦" },
    { domain: "google.co.ug", gl: "ug", name: "Uganda", flag: "🇺🇬" },
    { domain: "google.co.uk", gl: "uk", name: "United Kingdom", flag: "🇬🇧" }, // **Lưu ý:** Mã vùng cho UK là GB, nhưng Google dùng 'uk'
    { domain: "google.com.uy", gl: "uy", name: "Uruguay", flag: "🇺🇾" },
    { domain: "google.co.uz", gl: "uz", name: "Uzbekistan", flag: "🇺🇿" },
    { domain: "google.com.vc", gl: "vc", name: "Saint Vincent and the Grenadines", flag: "🇻🇨" },
    { domain: "google.co.ve", gl: "ve", name: "Venezuela", flag: "🇻🇪" },
    { domain: "google.vg", gl: "vg", name: "British Virgin Islands", flag: "🇻🇬" },
    { domain: "google.co.vi", gl: "vi", name: "United States Virgin Islands", flag: "🇻🇮" },
    { domain: "google.com.vn", gl: "vn", name: "Vietnam", flag: "🇻🇳" },
    { domain: "google.vu", gl: "vu", name: "Vanuatu", flag: "🇻🇺" },
    { domain: "google.ws", gl: "ws", name: "Samoa", flag: "🇼🇸" },
    { domain: "google.co.za", gl: "za", name: "South Africa", flag: "🇿🇦" },
    { domain: "google.co.zm", gl: "zm", name: "Zambia", flag: "🇿🇲" },
    { domain: "google.co.zw", gl: "zw", name: "Zimbabwe", flag: "🇿🇼" },
    { domain: "google.im", gl: "im", name: "Isle of Man", flag: "🇮🇲" },
    { domain: "google.je", gl: "je", name: "Jersey", flag: "🇯🇪" },
    { domain: "google.me", gl: "me", name: "Montenegro", flag: "🇲🇪" },
    { domain: "google.pn", gl: "pn", name: "Pitcairn Islands", flag: "🇵🇳" },
    { domain: "google.st", gl: "st", name: "São Tomé and Príncipe", flag: "🇸🇹" },
    { domain: "google.cat", gl: "cat", name: "Catalonia", flag: "🏴󠁥󠁳󠁣󠁴󠁿" } // Cờ Catalonia (có thể không hiển thị trên mọi thiết bị)
];
